name: helm-packaging

on:
  release: 
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      tag: ${GITHUB_REF}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Create package and push
        env:
          branch: gethub-penguins
        run: |
          git checkout main
          cp README.md ..
          cd ${GITHUB_WORKSPACE}/..
          helm package benthos-helm-chart
          cd benthos-helm-chart
          git checkout ${{ env.branch }}
          mv ../README.md .
          mv ../benthos-*.tgz .
          helm repo index . --url https://benthosdev.github.io/benthos-helm-chart/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bump chart version to ${{ env.tag }}"
          git push origin ${{ env.branch }}
