name: tagging

on: 
  pull_request:
    types:
      - closed

jobs:
  apply-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get chart.yaml tag
        run: |
          echo "chart_tag=$(grep '^version: ' ${GITHUB_WORKSPACE}/Chart.yaml | sed 's/version: //g')" >> $GITHUB_ENV
      - name: Check for tag
        run: |
          echo "repo_tag=$(git tag -l ${{ env.chart_tag }})" >> $GITHUB_ENV
      - name: Conditionally tag release
        if: env.chart_tag != env.repo_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.chart_tag }}
          release_name: ${{ env.chart_tag }}
          commitish: main
          body: ""
          draft: false
          prerelease: false
